perfume-pick/purple-front

- src/app/signIn/page.tsx
- src/app/signUp/page.tsx
- 로그인 signIn 폴더 추가
- 회원가입 signUp 폴더 추가 했습니다.
> feat: 로그인, 회원가입 폴더 추가

- .eslintrc.json
- next.config.js
- src/app/constant/commonTypes.ts
- src/app/layout.tsx
- src/app/page.tsx
- src/app/template.tsx
- src/component/atom/BoxComponents.tsx
- src/hook/screen/useDeviceType.ts
모바일 프로토타입 레이아웃 작성. (야놀자같은 앱과비슷하게 갈수있도록 작업)
> PURPLE-45: prototype layout template

- .github/workflows/ci.yaml
> ex) #PURPLE-41
- ci cd 빌드 및 push container reload 작업.
- 싱글 인스턴스이므로 무중단배포불가
> [PURPLE-41]: completed ci cd and run command

- src/components/atom/SearchBar/index.tsx
- src/components/atom/SearchBar/styles.ts
> [PURPLE-73] searchBar컴포넌트 제작

- src/app/_components/DetailPage/index.tsx
- src/constant/detailTypes.ts
- 상세 페이지 select 네비게이션 스타일, 기능 제작 (해당 컴포넌트가 클릭 되면 border-bottom, font-weight 스타일 변경)
> [FEAT] detailPage selectBar

- src/app/onBoarding/step/oneStep/_components/Card/Card.tsx
- src/app/onBoarding/step/oneStep/page.tsx
- src/app/onBoarding/step/styles.ts
- src/app/onBoarding/step/twoStep/page.tsx
- src/app/template.tsx
- src/components/navHeaderLayout/navHeaderLayout.tsx
- src/constant/onBoardingTypes.ts
- src/styles/emotion.d.ts
- src/styles/theme.ts
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> Feat: onBoarding페이지 제작

- src/app/onBoarding/step/oneStep/page.tsx
- src/components/alert/ConfirnAlert.tsx
- src/components/alert/styles.ts
- src/components/modalLayout/modalLayout.tsx
- src/constant/alert/alertText.ts
- src/types/alertTypes.ts
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> [FEAT] confirm alert 제작

- src/app/commentPage/page.tsx
- src/app/detail/page.tsx
- src/app/onBoarding/step/oneStep/page.tsx
- src/app/onBoarding/step/twoStep/page.tsx
- src/components/alert/Alert.tsx
- src/components/alert/styles.ts
- src/components/navHeaderLayout/navHeaderLayout.tsx
- src/constant/alert/alertText.ts
> #[PURPLE-109]
> alert 컴포넌트 제작
[PURPLE-109]: https://team-purple.atlassian.net/browse/PURPLE-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PURPLE-109] alert 컴포넌트 제작

- src/app/commentPage/page.tsx
- src/app/commentPage/styles.ts
- 값이 채워지기 전까지 button disabled 처리 
- 간단한 코멘트, 자세한 코멘트 분리 + 스타일 추가
> [FEAT] commentPage 기능+스타일 수정

- src/app/myPage/profileSetting/_components/ValidatedInput/ValidatedInput.tsx
- src/components/navHeaderLayout/navHeaderLayout.tsx
> Fix: 타입 에러 수정

- .github/workflows/ci.yaml
> - github actions 스크립트 내 ec2 ssh 해킹 접근 방지를 위한 동적 ip 적용을 위한 코드 추가
> [HOTFIX] github actions 스크립트 내 ec2 ssh 해킹 접근 방지를 위한 동적 ip 적용을 위한 코드 추가

- .github/workflows/ci.yaml
> - ci 설정 파일 들여 쓰기로 인한 빌드 오류 수정
> [HOTFIX] ci 설정 파일 들여 쓰기로 인한 빌드 오류 수정

- .github/workflows/ci.yaml
> [HOTFIX] 누락된 ci 파일 들여쓰기 수정 사항 추가

- src/app/global.css
- src/app/mainPage/page.tsx
- src/app/mainPage/styles.ts
- src/app/myPage/evaluationPerfumePage/page.tsx
- src/app/onBoarding/step/oneStep/page.tsx
- src/app/onBoarding/step/styles.ts
- src/app/onBoarding/step/twoStep/page.tsx
- src/app/searchPage/_components/ProductList/ProductHorizontalScroll.tsx
- src/app/searchPage/page.tsx
- src/app/searchPage/styles.ts
- src/components/Evaluation/EvaluatoinBanner.tsx
- src/components/atom/SearchBar/SearchBar.tsx
- src/components/atom/SearchBar/styles.ts
- src/components/molecule/ProductCard/ProductCard.tsx
- src/components/molecule/ProductCard/styles.ts
- src/components/organism/ChipList/ChipList.tsx
- src/components/organism/ProductCardGrid/ProductCardGrid.tsx
- src/components/organism/ProductCardGrid/styles.ts
- src/service/client/onBoarding.ts
- src/service/client/searchPerfume.ts
- src/types/req/onboarding.ts
- src/types/res/perfume.ts
- src/types/res/searchPerfume.ts
> #PURPLE-149
> - 검색어 입력 기능 완료
> - 최근 검색 기능 완료
> - 최근 본 상품 기능 api 연결 완료 (제품 상세 화면 작업 진행 시 마무리 예정)
> [PURPLE-149] 로그인 기능 데이터 구현

- .github/workflows/ci.yaml
>
> - 빌드 오류 이슈로 .yaml 파일 수정 (aws-region)
> chore: yaml 파일 수정

- .github/workflows/ci.yaml
>
> - public ECR 접속을 위해 로그인 시에만 Region을 us-east-1로 설정
> chore: public ECR 로그인 시 region 설정

- pnpm-lock.yaml
> ex)
> - pnpm-lock.yaml 파일 수정
> chore: pnpm-lock.yaml 파일 수정

- src/components/organism/ChipList/ChipList.tsx
> 
> - 깃 클론이 받아지지 않는 이슈가 있어 Chip 컴포넌트 import 경로 수정
> Fix: Chip 컴포넌트 import 경로 수정

- src/app/commentPage/page.tsx
- src/components/atom/Button/index.tsx
- src/components/atom/Rating/Rating.tsx
> commentPage 수정, button 컴포넌트 일부 변경, 별점 기능 추가
> Fix: commentPage 수정, button 컴포넌트 일부 변경, 별점 기능 추가

- package.json
- pnpm-lock.yaml
- src/app/commentPage/page.tsx
- src/app/layout.tsx
- src/components/atom/Button/index.tsx
- src/components/atom/Rating/Rating.tsx
- src/components/mobileBottomNav/MobileBottomNav.tsx
> 모바일 하단 네비게이션 제작 완료(세세한 부분은 추후 변경 필요. router도 변경 필요)
> [FEAT] mobile nav 제작완료

- src/app/detail/_components/DetailInfo/DetailInfo.tsx
- src/app/layout.tsx
- src/app/perpicks/auth/login/[type]/page.tsx
- src/app/signin/page.tsx
- src/components/alert/DialogAlert.tsx
- src/components/alert/Portal.tsx
- src/components/alert/styles.ts
- src/components/atom/Rating/EditableRating.tsx
- src/components/mobileBottomNav/MobileBottomNav.tsx
- src/components/molecule/MoreButton/MoreButton.tsx
- src/components/organism/CommentBox/CommentBox.tsx
- src/components/organism/ProductCardGrid/ProductCardGrid.tsx
- src/components/toast/OneLineTextToast.tsx
- src/constant/dropdown/commentFilterList.ts
- src/service/client/commentRegistration.ts
- src/service/client/perfumeDetail.ts
- src/service/client/signInService.ts
- src/types/alertTypes.ts
- src/types/req/signin.ts
- src/types/res/perfumeDetail.ts
- src/utils/http/clientHttp.ts
- src/utils/http/serverHttp.ts
> .
> 로그인 로직 변경으로 인해 1차적으로 먼저 PR 올립니다.
>
> - login과 login-try api에 request body 추가
> - accords-notes 삭제 후 detail api 추가
> - 클릭용 별점 컴포넌트(EditableRating.tsx) 1점 단위로 수정
> - 토스트, 모달 추가
> - 콘솔 정리
> [FEAT] 로그인 api request body 추가

- src/app/commentPage/_components/Product/Product.tsx
- src/app/commentPage/page.tsx
- src/app/detail/_components/Comment/DetailComment.tsx
- src/app/detail/_components/DetailTop/DetailPageBanner.tsx
- src/app/detail/_components/DetailTop/index.tsx
- src/app/detail/page.tsx
- src/app/mainPage/_components/perfume/Perfume.tsx
- src/components/molecule/ProductCard/ProductCard.tsx
- src/components/organism/CommentBox/CommentBox.tsx
- src/constant/dropdown/commentFilterList.ts
- src/utils/tokenService.ts
> .
> - 향수 상세 정보 api 데이터 수정
> - 코멘트 더보기 목록 수정
> - 모바일 테스트를 위해 jwt cookie secure 속성 임시 해제
> [FEAT] 향수 상세 정보 데이터 수정

- src/app/detail/page.tsx
- src/components/atom/ShareButton/ShareButton.tsx
> [FEAT] shareButton 컴포넌트 추가

- src/app/global.css
- src/app/layout.tsx
- src/app/mainPage/_components/perfumes/Perfumes.tsx
- src/app/mainPage/styles.ts
- src/app/searchPage/page.tsx
- src/app/searchPage/styles.ts
- src/components/mobileBottomNav/MobileBottomNav.tsx
- src/components/molecule/MoreButton/MoreButton.tsx
- src/components/molecule/ProductCard/styles.ts
- src/components/organism/CommentBox/CommentBox.tsx
> .
> - 이미지 url 도메인 수정
> - pretendard 웹폰트 body에 적용
> - bottomNav 컴포넌트 sticky 속성으로 수정 / 페이지 내에서 깨지는 부분 스타일 수정
> [FEAT] CSS 수정

- src/utils/http/logout.ts
> [FIX] 로그아웃 시 baseUrl 변경

- .env
- .github/workflows/ci.yaml
- .gitignore
- src/app/global.css
- src/app/myPage/profileSetting/page.tsx
- src/app/myPage/profileSetting/styles.ts
- src/app/myPage/styles.ts
- src/app/searchPage/styles.ts
- src/components/headerBottomContents/HeaderBottomContents.tsx
- src/components/molecule/ProductCard/ProductCard.tsx
- src/components/molecule/ProductCard/styles.ts
- src/components/organism/ProductCardGrid/styles.ts
> .
> - 프로필 페이지, 향수 카드 스타일 수정
> - .env 삭제
> - ci.yaml 파일 내 .env 파일 생성 코드 추가
> [CHORE] 페이지 스타일 및 배포파일 수정

- src/utils/http/clientHttp.ts
- src/utils/tokenService.ts
> .
> - 로그인 쿠키 secure 복구, samesite 속성 추가
> - 로그인 리프레쉬 무한 호출 방지를 위한 로직 수정
> [CHORE] 로그인 로직 수정

- src/app/detail/page.tsx
- src/components/atom/ShareButton/ShareButton.tsx
> [FEAT] 카카오 공유하기 형식 변경

- src/app/commentPage/page.tsx
> .
> - reviews api 변경 내용으로 코멘트 작성 페이지 접근 못하는 현상 수정
> [FIX] reviews api 변경 내용으로 코멘트 작성 페이지 접근 못하는 현상 수정

- src/utils/http/clientHttp.ts
> 
> - 클라이언트에서 모든 API 요청마다 토큰 만료를 2번 확인하고, 만료되었으면 로그아웃합니다.
> Feat: 모든 요청마다 토큰 만료 확인

- src/app/detail/_components/DetailInfo/DetailInfo.tsx
- src/app/detail/_components/DetailTop/DetailPageBanner.tsx
- src/app/global.css
- src/app/onBoarding/step/oneStep/page.tsx
- src/components/atom/Rating/ReadonlyRating.tsx
- src/components/mobileBottomNav/MobileBottomNav.tsx
- src/components/molecule/ProductCard/styles.ts
- src/types/res/perfume.ts
- src/types/res/perfumeDetail.ts
> .
> - body 영역 높이 수정
> - 읽기전용 벌점 컴포넌트 / 하단 네비게이션 바 숨김 페이지 추가
> - 최근 본 상품 함수명 최소 높이 지정
> - api 내 변경된 제품 정보명 변경 (온보딩 step1 브랜드 조회 API / 향수 상세 정보 조회 API)
> [STYLE] UI 수정 / api 반환값 내 수정된 제품 정보명 적용

- src/app/myPage/_components/Accord/Accord.tsx
- src/app/myPage/_components/ReviewCard/ReviewCard.tsx
- src/app/searchPage/_components/ProductList/ProductHorizontalScroll.tsx
- src/components/molecule/MoreButton/MoreButton.tsx
- src/components/organism/ChipList/ChipList.tsx
- src/hook/useHorizontalScroll.tsx
- src/types/res/profile.ts
> - Style: 마이페이지 어코드 퍼센트 기호 추가
> - 마이페이지 어코드 색상 수정 및 API 수정 **`(백엔드 API Response 수정 요청 필요)`**
> - 마이페이지 리뷰 클릭시 상세페이지로 리다이렉트
> - 검색 페이지 마우스로 좌우 스크롤 기능 구현
> [FIX] UI 수정 및 기능 추가

- src/app/myPage/_components/ReviewCard/ReviewCard.tsx
> - 마이페이지의 리뷰 카드에서 제품 상세 페이지로 리다이렉트되도록 URL 오류 수정했습니다
> Fix: 리뷰 카드에서 제품 상세 페이지로 리다이렉트

- src/app/myPage/_components/Accord/Accord.tsx
- src/app/myPage/_components/ReviewCard/ReviewCard.tsx
- src/app/myPage/_components/ReviewPerfume/ReviewPerfume.tsx
- src/types/res/profile.ts
> - 어코드 한글 텍스트 추가
> - 마이페이지에서 리뷰 페이지로 이동하는 조건 수정
> - 리뷰 페이지에서 상품상세페이지로 이동하도록 수정
> [FIX] 마이페이지 API 및 기능 수정

- src/app/detail/_components/DetailInfo/styles.ts
- src/app/detail/page.tsx
- src/app/mainPage/_components/commentPerfumes/CommentPerfumes.tsx
- src/app/mainPage/_components/logo/Perpick.tsx
- src/app/mainPage/_components/notePerfumes/NotePerfumes.tsx
- src/app/mainPage/_components/perfume/Perfume.tsx
- src/app/mainPage/_components/perfume/styles.ts
- src/app/myPage/_components/Accord/Accord.tsx
- src/app/onBoarding/step/oneStep/page.tsx
- src/app/onBoarding/step/success/page.tsx
- src/app/searchPage/page.tsx
- src/components/atom/SearchBar/SearchBar.tsx
- src/types/res/recommend.ts
- src/utils/http/clientHttp.ts
- src/utils/http/serverHttp.ts
> ex) .
> - 온보딩 향수 평가 완료 텍스트 수정
> - 검색 히스토리 api 호출부 수정
> - clientHttp 에러 반환 로직 수정
> - 메인 페이지 사용자별 좋아하는 어코드 색상 변경
> - 온보딩 step 진행 시 선택한 브랜드 취소되지 않는 이슈 수정
> - Image 태그 관련 경고문 수정
> - 안드로이드 수직 정렬 이슈 수정
> [FIX] QA 이슈 수정

- .github/workflows/ci.yaml
- 'SSH to EC2 Instance and Update Docker Container' 단계에 sudo 명령어 추가
> [CHORE] docker 명령어 sudo 추가

- src/app/global.css
> .
> - iOS body 높이영역 대응 코드 추가
> Fix: iOS body 높이영역 수정

- src/app/global.css
- src/app/signin/styles.ts
> .
> - iOS 회색 영역 노출 이슈 대응 코드 변경
> Style: iOS 회색 영역 노출 이슈 대응 코드 변경
